language: node_js
node_js: "10"

osx_image: xcode10.2
dist: xenial
sudo: required

os:
  - linux
  - osx
  - windows

services:
  - xvfb

addons:
  chrome: stable

branches:
  only:
    - master
    - develop

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi

cache:
  directories:
    - ./node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.cache/_prebuilds

before_script:
  - export DISPLAY=:99.0

install:
  - npm set progress=false
  - npm install

script:
  - echo "Linting"
  - ng lint

  - echo "Unit Tests"
  - npm run test

  - echo "E2E Tests"
  - npm run e2e

  - echo "Building Dev"
  - if [[ "$TRAVIS_BRANCH" == "develop" ]]; then npm run build:dev; fi

  - echo "Building Prod"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi

    #- echo "Deploying Linux"
    #- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "TRAVIS_OS_NAME" == "linux" ]]; then npm run electron:linux; fi

  - echo "Deploying Windows"
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "TRAVIS_OS_NAME" == "windows" ]]; then npm run electron:windows; fi

    #- echo "Deploying Mac"
    #- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "TRAVIS_OS_NAME" == "osx" ]]; then npm run electron:mac; fi

