language: node_js
node_js: "10"

#osx_image: xcode10.2
dist: xenial
sudo: required

os:
  - linux
    #- osx

services:
  - xvfb

addons:
  chrome: stable

branches:
  only:
    - master
    - develop

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.cache/_prebuilds

before_script:
  - export DISPLAY=:99.0

install:
  - npm set progress=false
  - npm install

script:
  - ng lint

  - npm run test

  - npm run e2e

  - npm run build:dev
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi

  - npm run electron:linux
  - npm run electron:windows
  - npm run electron:mac
